version: "2"
services:

# ======================================================================================================================
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ../../
      dockerfile: ./docker/dev/frontend/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../../services/frontend/app:/opt/deluge/services/frontend/app
      - ../../services/frontend/test:/opt/deluge/services/frontend/test
      - ../../services/frontend/Gruntfile.js:/opt/deluge/services/frontend/Gruntfile.js
    links:
      - "backend:docker.backend"

# ======================================================================================================================
  # Base  backend service which include the parameteres that backend and celery worker share
  base-backend:
    image: base-backend
    build:
      context: ../..
      dockerfile: ./docker/dev/backend/Dockerfile
    volumes:
      - ../../services/backend/src:/opt/deluge/services/backend/src
      - ../../services/backend/libs/:/opt/deluge/services/backend/libs/
    environment:
      - PYTHONUNBUFFERED=false
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  # Backend DJANGO service
  backend:
    extends: base-backend
    container_name: backend
    links:
      - "postgres:docker.postgres"
#      - "router:docker.router"
#      - "rabbitmq:docker.celery.broker"
#      - "redis:docker.celery.backend"
#      - "ethwallet:docker.ethwallet"
#      - "worker-backend"
    environment:
      - SOCIAL_AUTH_GITHUB_OAUTH2_SECRET=${SOCIAL_AUTH_GITHUB_OAUTH2_SECRET}
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=${SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET}
      - SOCIAL_AUTH_TWITTER_OAUTH1_SECRET=${SOCIAL_AUTH_TWITTER_OAUTH1_SECRET}
      - SOCIAL_AUTH_TWITTER_OAUTH1_KEY=${SOCIAL_AUTH_TWITTER_OAUTH1_KEY}
      - COINBASE_API_KEY=${COINBASE_API_KEY}
      - COINBASE_API_SECRET=${COINBASE_API_SECRET}
      - ETH_NOTIFICATION_TOKEN=${ETH_NOTIFICATION_TOKEN}
      - BTC_NOTIFICATION_TOKEN=${BTC_NOTIFICATION_TOKEN}
      - ETHWALLET_API_KEY=${ETHWALLET_API_KEY}
      - ETHWALLET_API_SECRET=${ETHWALLET_API_SECRET}
      - WHOAMI=DJANGO
    entrypoint: ["python3", "-u", "manage.py"]
    command: ["runserver" , "0.0.0.0:3000"]

  # Celery worker
  worker-backend:
    extends: base-backend
    container_name: worker-backend
    links:
      - "postgres:docker.postgres"
      - "router:docker.router"
      - "rabbitmq:docker.celery.broker"
      - "redis:docker.celery.backend"
    environment:
      - CELERY_TEST=True
      - WHOAMI=CELERY
    entrypoint: ["celery"]
    command: ["-A" , "absortium.celery.app", "worker", "--loglevel=info", "-c", "3"]

# ======================================================================================================================
  base-ethwallet:
    image: base-ethwallet
    build:
      context: ../..
      dockerfile: ./docker/dev/ethwallet/Dockerfile
    environment:
      - PYTHONUNBUFFERED=false
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ../../services/backend/libs/core:/opt/deluge/services/backend/libs/core
      - ../../services/ethwallet/:/opt/deluge/services/ethwallet/

  ethwallet:
    extends: base-ethwallet
    container_name: ethwallet
    environment:
      - WHOAMI=DJANGO
    links:
      - "rabbitmq:docker.celery.broker"
      - "postgres:docker.postgres"
#      - "redis:docker.celery.backend"
#      - "ethnode:docker.ethnode"
#      - "worker-ethwallet"
    volumes_from:
      - ethnode
    entrypoint: ["python3", "-u", "manage.py"]
    command: ["runserver" , "0.0.0.0:3000"]

  worker-ethwallet:
      extends: base-ethwallet
      container_name: worker-ethwallet
      environment:
        - WHOAMI=CELERY
        - C_FORCE_ROOT=True
      links:
        - "rabbitmq:docker.celery.broker"
        - "postgres:docker.postgres"
#        - "redis:docker.celery.backend"
#        - "ethnode:docker.ethnode"
      volumes_from:
        - ethnode
      entrypoint: ["celery"]
      command: ["-A" , "ethwallet.celery.app", "worker", "--loglevel=info", "-c", "3"]

# ======================================================================================================================
  router:
    container_name: router
    image: router
    build:
      context: ../..
      dockerfile: ./docker/dev/router/Dockerfile
    volumes:
      - ../../services/router:/opt/deluge/services/router
    ports:
      - "8080:8080"

# ======================================================================================================================
  ethnode:
    container_name: ethnode
    image: ethnode
    build:
      context: ../..
      dockerfile: ./docker/dev/ethnode/Dockerfile
    ports:
      - "8545:8545"
    volumes:
      - ../../services/ethnode/genesis.json:/opt/deluge/services/ethnode/genesis.json
      - ../../services/ethnode//keystore:/opt/deluge/services/ethnode/keystore
#    command: [
#      "geth",
#      "--dev",
#      "--networkid", "123",
#      "--nodiscover",
#      "--mine",
#      "--maxpeers", "0",
#      "--datadir", ".",
#      "--rpc",
#      "--rpcapi", "personal,db,eth",
#      "--rpcaddr" ,"0.0.0.0",
#      "--rpcport", "8545"
#    ]

    command: [
      "geth",
      "--dev",
      "--mine",
      "--datadir", ".",
      "--rpc",
      "--rpcapi", "personal,db,eth",
      "--rpcaddr" ,"0.0.0.0",
      "--rpcport", "8545"
    ]


# ======================================================================================================================
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

# ======================================================================================================================
  redis:
    container_name: redis
    image: redis

# ======================================================================================================================
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq

# ==================================================================================================================== #
#                                                    RUBBISH                                                           #
# ==================================================================================================================== #
  flower:
    container_name: flower
    image: worker
    build:
      context: ../..
      dockerfile: ./docker/dev/celery/Dockerfile
    links:
      - "rabbitmq:docker.celery.broker"
    ports:
      - "5555:5555"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    volumes:
      - ../../services/backend/src:/opt/deluge/services/backend/src
      - ../../services/backend/libs/core:/opt/deluge/services/backend/libs/core
    command: ["flower", "-A" , "absortium.celery.app", "--address=0.0.0.0", "--port=5555", "--broker=amqp://guest@docker.celery.broker"]

# ======================================================================================================================
  datadog:
    container_name: datadog
    image: datadog/docker-dd-agent
    environment:
     - API_KEY=${DATADOG_API_KEY}
     - DOGSTATSD_ONLY=true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc:/host/proc:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro}

volumes:
  dbdata:
    driver: local
  ethereumdata:
    driver: local