__author__ = 'andrew.shvv@gmail.com'

from decimal import Decimal

BTC_ETH = 0
BTC_XMR = 1
AVAILABLE_PAIRS = {
    'btc_eth': BTC_ETH,
    'btc_xmr': BTC_XMR,
}

SELL = 0
BUY = 1
AVAILABLE_ORDER_TYPES = {
    'sell': SELL,
    'buy': BUY
}

EXCHANGE_INIT = 0
EXCHANGE_PENDING = 1
EXCHANGE_COMPLETED = 2

AVAILABLE_TASK_STATUS = {
    'init': EXCHANGE_INIT,
    'pending': EXCHANGE_PENDING,
    'completed': EXCHANGE_COMPLETED
}

CELERY_RETRY_COUNTDOWN = 0.1
CELERY_MAX_RETRIES = 1000

BTC = 0
ETH = 1
AVAILABLE_CURRENCIES = {
    'btc': BTC,
    'eth': ETH
}

MAX_DIGITS = 15
DECIMAL_PLACES = 8

OFFER_MAX_DIGITS = MAX_DIGITS + (MAX_DIGITS - DECIMAL_PLACES)
ACCOUNT_MAX_DIGITS = OFFER_MAX_DIGITS

AMOUNT_MIN_VALUE = float(Decimal("1") / (Decimal("10") ** DECIMAL_PLACES))
PRICE_MIN_VALUE = float(Decimal("1") / (Decimal("10") ** DECIMAL_PLACES))
