version: "2"
services:
  frontend:
    image: absortium/frontend:latest
    build:
      context: ${DELUGE_PATH}
      dockerfile: ./docker/containers/prod/frontend/Dockerfile

  backend:
    image: absortium/backend:latest
    build:
      context: ${DELUGE_PATH}
      dockerfile: ./docker/containers/prod/backend/Dockerfile

  ethwallet:
    image: absortium/ethwallet:latest
    build:
      context: ${DELUGE_PATH}
      dockerfile: ./docker/containers/prod/ethwallet/Dockerfile