version: "2"
services:
  backend:
      container_name: absortium
      image: andrewsamokhvalov/absortium
      build:
        context: ../..
        dockerfile: ./docker/prod/info/Dockerfile
      ports:
        - "80:8080"
      links:
        - "postgres:postgres"
        - "datadog:datadog"

  frontend:
    container_name: frontend
    image: andrewsamokhvalov/frontend
    build:
      context: ../../
      dockerfile: ./docker/prod/frontend/Dockerfile
    ports:
      - "80:9000"

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./mysql/:/var/lib/mysql

  datadog:
    container_name: datadog
    image: datadog/docker-dd-agent
    environment:
     - API_KEY=db9c2e6759a98891c8c49ab875d420aa
     - DOGSTATSD_ONLY=true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc:/host/proc:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro