version: "2"
services:
  frontend:
    image: absortium/base-frontend:latest

  backend:
    image: backend
    build:
      context: ${DELUGE_PATH}
      dockerfile: ./docker/containers/dev/backend/Dockerfile

  ethwallet:
    image: ethwallet
    build:
      context: ${DELUGE_PATH}
      dockerfile: ./docker/containers/dev/ethwallet/Dockerfile