version: "2"
services:

  frontend:
    ports:
      - "3000:80"
    links:
      - "m-backend:docker.backend"

  # Backend DJANGO service
  m-backend:
    links:
      - "postgres:docker.postgres"
      - "router:docker.router"
      - "rabbitmq:docker.celery.broker"
      - "redis:docker.celery.backend"
      - "w-backend"

  # Celery worker
  w-backend:
    links:
      - "postgres:docker.postgres"
      - "router:docker.router"
      - "rabbitmq:docker.celery.broker"
      - "redis:docker.celery.backend"
    environment:
      - MODE=frontend

  poloniexsync:
    links:
      - "postgres:docker.postgres"
      - "router:docker.router"

  router:
    ports:
      - "8080:8080"

  postgres:
    ports:
      - "5432:5432"

  redis:
      ports:
      - "6379:6379"