version: "2"
services:

  frontend:
    ports:
      - "3000:80"
    links:
      - "m-backend:docker.backend"

  # Backend DJANGO service
  m-backend:
    links:
      - "postgres:docker.postgres"
      - "router:docker.router"
      - "rabbitmq:docker.celery.broker"
      - "redis:docker.celery.backend"
      - "w-backend"

  # Celery worker
  w-backend:
    links:
      - "postgres:docker.postgres"
      - "router:docker.router"
      - "rabbitmq:docker.celery.broker"
      - "redis:docker.celery.backend"
    environment:
      - MODE=frontend

  router:
    ports:
      - "8080:8080"

  postgres:
    ports:
      - "5432:5432"

  notifier:
    extends: base-backend
    container_name: notifier
    links:
      - "postgres:docker.postgres"
      - "m-backend:docker.backend"

    environment:
      - WHOAMI=NOTIFIER
    entrypoint: ["python3"]
    command: ["manage.py", "mocknotifier"]

  redis:
      ports:
      - "6379:6379"