version: "2"
services:

  frontend:
    ports:
      - "80:80"
    links:
      - "m-backend:docker.backend"

  # Backend DJANGO general service (used for management)
  backend:
    links:
      - "postgres:docker.postgres"

  # Backend DJANGO service
  m-backend:
    links:
      - "postgres:docker.postgres"
      - "router:docker.router"
      - "rabbitmq:docker.celery.broker"
      - "redis:docker.celery.backend"
      - "m-ethwallet:docker.ethwallet"
      - "w-backend"
    environment:
      - MODE=testnet

  # Backend celery worker
  w-backend:
    links:
      - "postgres:docker.postgres"
      - "router:docker.router"
      - "rabbitmq:docker.celery.broker"
      - "redis:docker.celery.backend"
      - "m-ethwallet:docker.ethwallet"
    environment:
      - MODE=testnet

  # Ethwallet DJANGO general service (used for management)
  ethwallet:
    links:
      - "postgres:docker.postgres"

  # Ethereum wallet backend DJANGO service
  m-ethwallet:
    links:
      - "rabbitmq:docker.celery.broker"
      - "postgres:docker.postgres"
      - "redis:docker.celery.backend"
      - "ethnode:docker.ethnode"
      - "w-ethwallet"

  # Ethereum wallet celery worker
  w-ethwallet:
    links:
      - "rabbitmq:docker.celery.broker"
      - "postgres:docker.postgres"
      - "redis:docker.celery.backend"
      - "ethnode:docker.ethnode"


  poloniexbot:
    links:
      - "postgres:docker.postgres"
      - "m-backend:docker.backend"

  ethnode:
    ports:
      - "8545:8545"
    entrypoint: ["geth"]
    command: [
      "--fast",
      "--datadir", ".",
      "--testnet",
      "--rpc",
      "--rpcapi", "personal,db,eth",
      "--rpcaddr" ,"0.0.0.0",
      "--rpcport", "8545"
    ]

  redis:
    ports:
      - "6379:6379"
