version: "2"
services:
  
  backend:
    links:
      - "postgres:docker.postgres"
  
  ethwallet:
    links:
      - "postgres:docker.postgres"

  m-backend:
    links:
      - "postgres:docker.postgres"

  m-ethwallet:
    links:
      - "postgres:docker.postgres"

  poloniexbot:
    links:
      - "postgres:docker.postgres"

  postgres:
    ports:
      - "5000:5432"